manifest_version = "0"
plugin_version = "0.1.0"
slug = "administrivia"
name = "Administrivia"
description = "TAP administrative pages, panels, searches, and infrastructure."

[grift]
grid-landing = "grift/grid-landing.grift.json"
entity-pages = "grift/entity-pages.grift.json"
cares-administrivia = "grift/cares-administrivia.grift.json"
cares-administrivia-v04 = "grift/cares-administrivia-v04.grift.json"
batch-viewer-page = "grift/batch-viewer-page.grift.json"
batches-list-page = "grift/batches-list-page.grift.json"
plugins-page = "grift/plugins-page.grift.json"
